### PR TITLE
FIX: getTransaction error

### PR DESCRIPTION
**Pull request by nfm1337**
Made it follow official doc: [Solana Doc](https://docs.solana.com/api/http#gettransaction)

### CODE REVIEW

**Comment by skynetcap** [comment]
Looks good to me. I fixed the merge conflict in https://github.com/skynetcap/solanaj/tree/nfm1337-fix/getTransaction.

Will merge once the conflict is resolved. 🎉

**Comment by malafk** [comment]
Bump, testing error seems to be a ratelimit?

**Comment by nfm1337** [comment]
> Bump, testing error seems to be a ratelimit?
True
Log screenshot

**Review by skynetcap — APPROVED** [review]
LGTM

**Pull request merged**
